SEED: 7
OPTIMIZER: 'SGD'
OPTIMIZER_CONFIG:
  lr: 0.05
  # momentum: 0.1
  weight_decay: 0.00002

LOSS_FUNCTION: 'CrossEntropyLoss'

METRIC: 'metrics_1'

MODEL_VER:
  model_ver: 'model_ndgg_1'
  batch_loader: 'load_batch_data_ndgg_1'
  load_data_prep: 'load_data_ndgg_1'
  ligand: 'model_4v3'
  protein: 'model_4v3'
  cls: 'cls_1'
  output_dim: 2
  anneal_dropouts: [[0.1, 0], [0.1, 0.5]]

MODEL_CONFIG:
  atom_embedding_dim: 100

  config_ligand:
    output_dim: 50
    block_num: 4
    hidden_dim: 512
    aggregation_methods: ['sum', 'rnn-max']
    affine_before_merge: False
    multiple_aggregation_merge: 'cat'
    readout_method: 'rnn-sum-max'
    eps: 1.0
    add_dense_connection: True
    use_neighbor_op: False
    
  config_protein:
    output_dim: 55
    block_num: 3
    hidden_dim: 256
    aggregation_methods: ['sum', 'rnn-max']
    affine_before_merge: False
    multiple_aggregation_merge: 'cat'
    readout_method: 'rnn-sum-max'
    eps: 1.0
    add_dense_connection: True
    use_neighbor_op: False

  config_cls:
    h_sizes: [100, 75]
    output_dim: 2

TRAINING:
  batch_size: 256
  batch_size_min: 256
  batch_size_test: 256
  max_epoch_num: 100
  val_per_epoch_num: 1